name: Release the Monster ðŸ‘½

on:
    pull_request:
        branches:
            - main
    push:
        branches:
            - main

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Setup .Net 8.0
              uses: actions/setup-dotnet@v3
              with: 
                    dotnet-version: 8.x
            - name: Install dependencies
              run: dotnet restore ./src/StarisApi/StarisApi.csproj
            - name: Build
              run: dotnet build ./src/StarisApi/StarisApi.csproj --configuration Release --no-restore
            - name: Publish
              run: dotnet publish ./src/StarisApi/StarisApi.csproj --runtime win-x86 --self-contained --configuration Release --output ./publish

            - name: Deploy Sync Files
              uses: SamKirkland/FTP-Deploy-Action@v4.3.5
              with:
                    server: site3829.siteasp.net
                    server-dir: ./wwwroot/
                    username: ${{ secrets.ftp_user }}
                    password: ${{ secrets.ftp_password }}
                    local-dir: ./publish/
